resources:
  - ../../base

configMapGenerator:
  - name: db-config
    behavior: merge
    literals:
      - DB_HOST=rds-prod.eu-west-1.rds.amazonaws.com

patches:
  - target:
      kind: ExternalSecret
      name: db-credentials-external
    patch: |-
      apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      metadata:
        name: db-credentials-external
      spec:
        secretStoreRef:
          name: prod-aws-secret-store

namePrefix: prod-
namespace: production
