apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials-external
  namespace: default
spec:
  refreshInterval: 1h # How often to poll AWS for updates
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: db-credentials # This matches what product-deployment.yaml expects!
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD # The key created inside the k8s secret
      remoteRef:
        key: ecommerce/db-credentials # The name of the secret in AWS Secrets Manager
        property: password # If the AWS secret is JSON, this pulls a specific property. Omit if it's plain text.
